---
- name: Set Hostname with hostname command
  hostname:
    name: "{{ hostname }}"
  notify:
    - restart hostname
    - restart systemd-logind

- name: Re-gather facts
  action: setup
  when: ansible_hostname != fqdn

- name: Build hosts file (backups will be made)
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ public_ip }}"
    line: "{{ public_ip }} {{ fqdn }} {{ hostname }}"
    state: present
    backup: yes
  when: ansible_default_ipv4.address is defined
  notify:
    - restart hostname
    - restart systemd-logind
